image: python:3.10  # Utilisation de l'image Python

stages:
  - generate
  - test
  - deploy

generate_json:
  stage: generate
  script:
    - echo "Création des répertoires nécessaires"
    - mkdir -p public/travaux
    - python generate_json.py
    - echo "Affichage du contenu de public avant déplacement :"
    - ls -lh public
    - echo "Affichage du contenu de public/html_pages :"
    - ls -lh public/html_pages || echo "Le dossier public/html_pages est vide"
    - mv public/html_pages/* public/ || echo "Aucun fichier à déplacer"
    - echo "Affichage du contenu de public après déplacement :"
    - ls -lh public
  artifacts:
    paths:
      - public/documents.json
      - public/*.html

pages:
  stage: deploy
  script:
    - echo "Déploiement des fichiers suivants :"
    - ls -lhR public  # Vérifie le contenu avant déploiement
  artifacts:
    paths:
      - public
  only:
    - main  # Assure que la tâche ne s’exécute que sur la branche principale
